-- Drop existing tables and types if they exist, for idempotency
drop table if exists public.stock_entries;
drop table if exists public.profiles;
drop type if exists public.user_role;
drop type if exists public.location;

-- Create ENUM types for roles and locations for better data integrity
create type public.user_role as enum ('Admin', 'Manager', 'Data Entry');
create type public.location as enum ('MBUTOH', 'SOKO');

-- Create a table for public profiles
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  role user_role not null default 'Data Entry',
  assigned_location location,
  primary key (id)
);
comment on table public.profiles is 'Stores public-facing profile information for each user.';
comment on column public.profiles.id is 'References the internal auth.users table.';

-- Create the main table for stock entries
create table public.stock_entries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  date date not null,
  location location not null,
  brand text not null,
  model text not null,
  color text,
  imei text,
  opening_stock integer not null default 0,
  incoming_stock integer not null default 0,
  sold integer not null default 0,
  returned integer not null default 0,
  closing_stock integer generated always as (
    (coalesce(opening_stock, 0) + coalesce(incoming_stock, 0)) - (coalesce(sold, 0) + coalesce(returned, 0))
  ) stored,
  source text not null,
  notes text
);
comment on table public.stock_entries is 'Tracks daily mobile phone stock and sales data.';

-- Set up a trigger to automatically create a profile when a new user signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'Data Entry');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.stock_entries enable row level security;

-- Create RLS policies for the profiles table
create policy "Users can view their own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Admins can view all profiles" on public.profiles
  for select to authenticated
  using (
    (select role from public.profiles where id = auth.uid()) = 'Admin'
  );

create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Admins can update any profile" on public.profiles
  for update to authenticated
  using (
    (select role from public.profiles where id = auth.uid()) = 'Admin'
  );

-- Create RLS policies for the stock_entries table
create policy "Allow all access for Admins" on public.stock_entries
  for all using (
    (select role from public.profiles where id = auth.uid()) = 'Admin'
  );

create policy "Allow read access for Managers" on public.stock_entries
  for select using (
    (select role from public.profiles where id = auth.uid()) = 'Manager'
  );

create policy "Allow access for assigned location" on public.stock_entries
  for all using (
    (select assigned_location from public.profiles where id = auth.uid()) = location
  );

-- Allow authenticated users to insert records (specific location policy will apply)
create policy "Allow insert for authenticated users" on public.stock_entries
  for insert with check (true);
